DatabaseConsistencySettings:
  color: true
  log_level: DEBUG

DatabaseConsistencyCheckers:
  MissingIndexChecker:
    enabled: true
  MissingUniqueIndexChecker:
    enabled: true
  ColumnPresenceChecker:
    enabled: true
  NullConstraintChecker:
    enabled: true
  BelongsToPresenceChecker:
    enabled: true
  LengthConstraintChecker:
    enabled: true

User:
  lower(email):
    MissingUniqueIndexChecker:
      enabled: false
