parallel: true
format: progress
default_ignores: false

ignore:
  - 'db/schema.rb'
  - 'vendor/**/*'
  - 'node_modules/**/*'
  - 'log/**/*'
  - 'tmp/**/*'
  - 'public/**/*'
  - '.docker/**/*'
  - 'app/javascript/**/*'