version: '3.4'

services:
  rails:
    build:
      context: .
      cache_from:
        - {$DOCKER_USERNAME}/ohmuritel-test:1.0.1
      args:
        RUBY_VERSION: '2.6.5'
        PG_MAJOR: '11'
        NODE_MAJOR: '11'
        YARN_VERSION: '1.19.1'
        BUNDLER_VERSION: '2.0.2'
        BUNDLE_WITHOUT: 'development'
        RAILS_ENV: 'test'
    stdin_open: true
    tty: true
    environment:
      NODE_ENV: test
      RAILS_ENV: test
      REDIS_URL: redis://redis:6379/
      DATABASE_URL: postgres://postgres:postgres@postgres:5432
      BOOTSNAP_CACHE_DIR: /bundle/bootsnap
      WEBPACKER_DEV_SERVER_HOST: webpacker
      WEB_CONCURRENCY: 1
      HISTFILE: /app/log/.bash_history
      PSQL_HISTFILE: /app/log/.psql_history
      EDITOR: vi
    image: {$DOCKER_USERNAME}/ohmuritel-test:1.0.1
    depends_on:
      - postgres
      - redis
    ports:
      - '3000:3000'

  postgres:
    image: postgres:11.1-alpine
    environment:
      PSQL_HISTFILE: /root/log/.psql_history
    ports:
      - 5432

  redis:
    image: redis:3.2-alpine
    ports:
      - 6379